version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
      ports:
        -"5432:5432"
      volumes:
        -db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: backend
    environment:
      DB_HOST: DB
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: ecommerce
    ports:
      - "8000:8000"
    depends_on:
      -  db
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  volumes:
    db_data:
